### ISSUE TITLE
Start up error

### ISSUE THREAD

**Issue by Tobe2d** [s9roll7/sd_loopback_music_sync_wave#3]
When I start SD I get this error on the log:

```
Error calling: E:\stable-diffusion-webui\extensions\sd_loopback_music_sync_wave\scripts\loopback_music_sync_wave.py/ui
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\scripts.py", line 271, in wrap_call
    res = func(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd_loopback_music_sync_wave\scripts\loopback_music_sync_wave.py", line 1179, in ui
    us_method = gr.Radio(label='Method', choices=['latent',*[x.name for x in sd_upscalers]], value=sd_upscalers[0].name, type="value")
IndexError: list index out of range
```

**Comment by s9roll7** [comment]
Thanks for the report.
I updated webui to the latest version and it happened in my environment too...

**Comment by s9roll7** [comment]
fixed

**Comment by Tobe2d** [comment]
Yes I can confirm the fix ;-)

Thank you!
