### ISSUE TITLE
please help me 

### ISSUE THREAD

**Issue by loveshe12** [s9roll7/sd_loopback_music_sync_wave#6]
*** Error loading script: loopback_music_sync_wave_ui.py
    Traceback (most recent call last):
      File "D:\program\sd-webui-aki-v4\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\program\sd-webui-aki-v4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\program\sd-webui-aki-v4\extensions\sd_loopback_music_sync_wave-main\scripts\loopback_music_sync_wave_ui.py", line 8, in <module>
        from scripts.util_sd_loopback_music_sync_wave.wave_generator import wave_generator_process
      File "D:\program\sd-webui-aki-v4\extensions\sd_loopback_music_sync_wave-main\scripts\util_sd_loopback_music_sync_wave\wave_generator.py", line 4, in <module>
        import scripts.util_sd_loopback_music_sync_wave.audio_analyzer
      File "D:\program\sd-webui-aki-v4\extensions\sd_loopback_music_sync_wave-main\scripts\util_sd_loopback_music_sync_wave\audio_analyzer.py", line 1, in <module>
        import librosa
      File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\librosa\__init__.py", line 209, in <module>
        from . import core
      File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\librosa\core\__init__.py", line 5, in <module>
        from .convert import *  # pylint: disable=wildcard-import
      File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\librosa\core\convert.py", line 7, in <module>
        from . import notation
      File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\librosa\core\notation.py", line 8, in <module>
        from ..util.exceptions import ParameterError
      File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\librosa\util\__init__.py", line 78, in <module>
        from .files import *  # pylint: disable=wildcard-import
      File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\librosa\util\files.py", line 11, in <module>
        import pooch
    ModuleNotFoundError: No module named 'pooch'

I am a code novice. May I know how to solve this situation

**Comment by loveshe12** [comment]
i already install pooch,but The above problems still arise
